name: flutter_releaser
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  args: ^2.3.2
  cli_util: ^0.3.5
  console: ^4.1.0
  path: ^1.8.3
  pubspec_parse: ^1.2.1
  yaml_writer: ^1.0.3
